# Site settings
title: SurpriseHighway.github.io
email: hello@surprisehighway.com
description: > # SurpriseHighway.github.io is a selection of of
    development tools, code libraries, and utilities
    that we use everyday at Surprise Highway.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://surprisehighway.github.io/" # the base hostname & protocol for your site
github_username:  surprisehighway

# Build settings
exclude: [node_modules, .sass-cache]
markdown: kramdown
collections:
    frontend:
        output: false
    cms:
        output: false
    developer-environments:
        output: false